spring:
  application:
    name: eureka-server

server:
  port: 8761
eureka:
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}
  client:
    fetch-registry: false
    register-with-eureka: false
